const data = [
  { word: "你好", viet: "Xin chào", pronounce: "nǐ hǎo" },
  { word: "谢谢", viet: "Cảm ơn", pronounce: "xièxie" },
  { word: "再见", viet: "Tạm biệt", pronounce: "zàijiàn" },
  { word: "请", viet: "Làm ơn / Mời", pronounce: "qǐng" },
  { word: "对不起", viet: "Xin lỗi", pronounce: "duìbuqǐ" },
  { word: "我", viet: "Tôi", pronounce: "wǒ" },
  { word: "你", viet: "Bạn", pronounce: "nǐ" },
  { word: "他", viet: "Anh ấy", pronounce: "tā" },
  { word: "她", viet: "Cô ấy", pronounce: "tā" },
  { word: "我们", viet: "Chúng tôi", pronounce: "wǒmen" },
  { word: "你们", viet: "Các bạn", pronounce: "nǐmen" },
  { word: "他们", viet: "Họ (nam)", pronounce: "tāmen" },
  { word: "她们", viet: "Họ (nữ)", pronounce: "tāmen" },
  { word: "是", viet: "Là", pronounce: "shì" },
  { word: "不是", viet: "Không phải", pronounce: "bú shì" },
  { word: "有", viet: "Có", pronounce: "yǒu" },
  { word: "没有", viet: "Không có", pronounce: "méiyǒu" },
  { word: "好", viet: "Tốt", pronounce: "hǎo" },
  { word: "不好", viet: "Không tốt", pronounce: "bù hǎo" },
  { word: "喜欢", viet: "Thích", pronounce: "xǐhuān" },
  { word: "不喜欢", viet: "Không thích", pronounce: "bù xǐhuān" },
  { word: "吃", viet: "Ăn", pronounce: "chī" },
  { word: "喝", viet: "Uống", pronounce: "hē" },
  { word: "水", viet: "Nước", pronounce: "shuǐ" },
  { word: "饭", viet: "Cơm", pronounce: "fàn" },
  { word: "茶", viet: "Trà", pronounce: "chá" },
  { word: "咖啡", viet: "Cà phê", pronounce: "kāfēi" },
  { word: "牛奶", viet: "Sữa", pronounce: "niúnǎi" },
  { word: "面包", viet: "Bánh mì", pronounce: "miànbāo" },
  { word: "鸡蛋", viet: "Trứng", pronounce: "jīdàn" },
  { word: "苹果", viet: "Táo", pronounce: "píngguǒ" },
  { word: "香蕉", viet: "Chuối", pronounce: "xiāngjiāo" },
  { word: "电脑", viet: "Máy tính", pronounce: "diànnǎo" },
  { word: "手机", viet: "Điện thoại", pronounce: "shǒujī" },
  { word: "书", viet: "Sách", pronounce: "shū" },
  { word: "笔", viet: "Bút", pronounce: "bǐ" },
  { word: "桌子", viet: "Cái bàn", pronounce: "zhuōzi" },
  { word: "椅子", viet: "Cái ghế", pronounce: "yǐzi" },
  { word: "门", viet: "Cửa", pronounce: "mén" },
  { word: "窗户", viet: "Cửa sổ", pronounce: "chuānghu" },
  { word: "学校", viet: "Trường học", pronounce: "xuéxiào" },
  { word: "老师", viet: "Giáo viên", pronounce: "lǎoshī" },
  { word: "学生", viet: "Học sinh", pronounce: "xuésheng" },
  { word: "朋友", viet: "Bạn bè", pronounce: "péngyǒu" },
  { word: "家", viet: "Nhà", pronounce: "jiā" },
  { word: "妈妈", viet: "Mẹ", pronounce: "māma" },
  { word: "爸爸", viet: "Bố", pronounce: "bàba" },
  { word: "哥哥", viet: "Anh trai", pronounce: "gēge" },
  { word: "姐姐", viet: "Chị gái", pronounce: "jiějie" },
  { word: "弟弟", viet: "Em trai", pronounce: "dìdi" },
  { word: "妹妹", viet: "Em gái", pronounce: "mèimei" },
  { word: "猫", viet: "Mèo", pronounce: "māo" },
  { word: "狗", viet: "Chó", pronounce: "gǒu" },
  { word: "车", viet: "Xe", pronounce: "chē" },
  { word: "火车", viet: "Tàu hỏa", pronounce: "huǒchē" },
  { word: "飞机", viet: "Máy bay", pronounce: "fēijī" },
  { word: "出租车", viet: "Taxi", pronounce: "chūzūchē" },
  { word: "走", viet: "Đi bộ", pronounce: "zǒu" },
  { word: "跑", viet: "Chạy", pronounce: "pǎo" },
  { word: "来", viet: "Đến", pronounce: "lái" },
  { word: "去", viet: "Đi", pronounce: "qù" },
  { word: "看", viet: "Xem", pronounce: "kàn" },
  { word: "听", viet: "Nghe", pronounce: "tīng" },
  { word: "说", viet: "Nói", pronounce: "shuō" },
  { word: "读", viet: "Đọc", pronounce: "dú" },
  { word: "写", viet: "Viết", pronounce: "xiě" },
  { word: "工作", viet: "Làm việc", pronounce: "gōngzuò" },
  { word: "学习", viet: "Học tập", pronounce: "xuéxí" },
  { word: "睡觉", viet: "Ngủ", pronounce: "shuìjiào" },
  { word: "起床", viet: "Thức dậy", pronounce: "qǐchuáng" },
  { word: "洗澡", viet: "Tắm", pronounce: "xǐzǎo" },
  { word: "刷牙", viet: "Đánh răng", pronounce: "shuāyá" },
  { word: "穿", viet: "Mặc", pronounce: "chuān" },
  { word: "衣服", viet: "Quần áo", pronounce: "yīfu" },
  { word: "鞋", viet: "Giày", pronounce: "xié" },
  { word: "帽子", viet: "Mũ", pronounce: "màozi" },
  { word: "天气", viet: "Thời tiết", pronounce: "tiānqì" },
  { word: "太阳", viet: "Mặt trời", pronounce: "tàiyáng" },
  { word: "月亮", viet: "Mặt trăng", pronounce: "yuèliang" },
  { word: "雨", viet: "Mưa", pronounce: "yǔ" },
  { word: "雪", viet: "Tuyết", pronounce: "xuě" },
  { word: "风", viet: "Gió", pronounce: "fēng" },
  { word: "热", viet: "Nóng", pronounce: "rè" },
  { word: "冷", viet: "Lạnh", pronounce: "lěng" },
  { word: "今天", viet: "Hôm nay", pronounce: "jīntiān" },
  { word: "昨天", viet: "Hôm qua", pronounce: "zuótiān" },
  { word: "明天", viet: "Ngày mai", pronounce: "míngtiān" },
  { word: "现在", viet: "Bây giờ", pronounce: "xiànzài" },
  { word: "早上", viet: "Buổi sáng", pronounce: "zǎoshang" },
  { word: "中午", viet: "Buổi trưa", pronounce: "zhōngwǔ" },
  { word: "晚上", viet: "Buổi tối", pronounce: "wǎnshang" },
  { word: "时间", viet: "Thời gian", pronounce: "shíjiān" },
  { word: "年", viet: "Năm", pronounce: "nián" },
  { word: "月", viet: "Tháng", pronounce: "yuè" },
  { word: "日", viet: "Ngày", pronounce: "rì" },
  { word: "星期", viet: "Tuần", pronounce: "xīngqī" },
  { word: "一点", viet: "Một giờ", pronounce: "yī diǎn" },
  { word: "分钟", viet: "Phút", pronounce: "fēnzhōng" },
  { word: "秒", viet: "Giây", pronounce: "miǎo" },
];

export default data;
